name: aldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.10
  - pip=20.3
  - pytorch=2.0.0
  - torchvision=0.15.0
  - numpy=1.23.5
  - pip:
      - gradio==3.32.0
      - opencv-python==4.7.0.72
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.8
      - pytorch-lightning==1.5.0
      - omegaconf==2.3.0
      - test-tube>=0.7.5
      - streamlit==1.20.0
      - einops==0.6.0
      - transformers==4.26.1
      - webdataset==0.2.48
      - kornia==0.6
      - open_clip_torch==2.16.0
      - invisible-watermark>=0.1.5
      - streamlit-drawable-canvas==0.8.0
      - torchmetrics==0.6.0
      - timm==0.4.12
      - addict==2.4.0
      - yapf==0.32.0
      - prettytable==3.6.0
      - safetensors==0.2.7
      - basicsr==1.4.2
      - pyrallis==0.3.1
      - scikit-learn==1.2.2
      - natsort==8.4.0
